### PR TITLE
Improve request parsing

### LINKED ISSUE #14: req is non-serializable
`req` extra is `**non-serializable**`, so it should not be set as extra.

image

Also I have very high memory and CPU consumption while this task (serialization of `req`) with results of crash of the app (`Allocation failed - JavaScript heap out of memory`). I have to say, that it happens not after first catched exception, but after second or third.
If I [comment out this line](https://github.com/mentos1386/nest-raven/blob/9ea75fc0dab0be0a3628af8d2ca8104b12f0006f/lib/raven.interceptor.ts#L39), all works perfectly.
To fix that, interceptor should set only some serializable and neccessary parameters of request (url/called action (if rpc))

P.S. error occured on http mvc website with express as nest backend.
P.P.S. I can PM you a video demonstation, if you want; I don't have time for creating demo repository right now, honestly

### PR DESCRIPTION
**Pull request by mentos1386**
Fixes #14 

- [x] Http, Ws, Rpc
- [ ] Graphql
- [ ] Docs

### CODE REVIEW

**Comment by mentos1386** [comment]
@maksimkurb Hey, can you help me out with graphql. I'm struggling to find what exactly graphql provides inside context. Do you by any chance know?

Documentation no the best for this...

**Comment by maksimkurb** [comment]
Hi.
```ts
const gqlHost = GqlArgumentsHost.create(host)
const ctx = gqlHost.getContext() /*
{
  req: IncomingMessage (from http) {
   headers,
   host,
   ip,
   method,
   body {
     operationName: string maybe?,
     query: string,
     variables: Object
   },
   ...other fields
  },
  _extensionStack: GraphQLExtensionStack
}
*/
const info = gqlHost.getInfo() /*
  {
    fieldName: string, // which field caused exception,
    ...other fields, don't looked into it
  }
*/

const args = gqlHost.getArgs() /*
  {
    arg1: "value1",
    arg2: 30
  }
*/
const root = gqlHost.getRoot() /* should contain root entity of the failed field */
```

**Comment by mentos1386** [comment]
@maksimkurb what do you think about this https://github.com/mentos1386/nest-raven/pull/15/files#diff-12cd056c46c4a42de12aa07827df2170R53 ?

**Comment by maksimkurb** [comment]
Have such information on GraphQL exceptions:
image
`req` does not contain graphql query, so it is unclear which `"requests"` field is failed
I think, Sentry report should contain full query and (if it's not hard to implement) field path (like "QueryRoot > users > 0 > requests")

Also RavenInterceptor does not intercept errors on my entity fields (if I write `@Field` function on entity but not on resolver). Is it intended or a bug (or I'm doing something wrong)?
`AppResolver` has `@UseInterceptors(new RavenInterceptor({ context: 'GraphQL' }))` decorator and `users` query field, then I'm requesting ` users { failingField } ` where `failingField` looks like this:
```ts
  @Field()
  public failingField(): string {
    throw new ForbiddenException('Test error')
  }
```

**Comment by mentos1386** [comment]
Merged this for the sake of ever releasing v5, will create new Issue to track better graphql support.

**Pull request merged**
